export const appText = {
  header: {
    login: 'Login',
    signUp: 'Sign Up',
    ourOffers: 'Our offers',
    startYourFreeTrial: 'Start your free trial',
  },
  footer: {
    footNote: '©2024 CORE PLATFORM · All rights reserved.',
    termsOfUse: 'Terms of use',
    privacyPolicy: 'Privacy policy',
    security: 'Security',
  },
  landingPage: {
    infoPanel: {
      chipLabel: 'Lorem ipsum is simply dummy tex',
      greatSupport: 'Great support on long term partnerships',
      makeTheRightMove: 'Make the right move',
      note: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      startFreeTrial: 'Start your free trial',
      ourOffers: 'Our offers',
    },
    aboutUs: {
      chipText: 'Who are we',
      aboutUs: 'About us',
      note: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknownLorem Ipsum is simply industry.",
      aboutUsText:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      learnMore: 'Learn more',
    },
    contactUs: {
      contactUs: 'Contact us',
      note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      namePlaceHolder: 'Name',
      emailPlaceHolder: 'Email',
      typeYourMessageHere: 'Type your message here',
      letsConnect: "Let's connect",
    },
    howWeWork: {
      workFlow: 'Work flow',
      howWeWork: 'How we work?',
      note: 'Specify helps you gain control of your design system across teams and products.',
      bookADemo: 'Book a demo',
    },
  },
  homePage: {
    createWorkspace: 'Create Workspace',
    profileHeader: {
      name: 'Senad Senadovic',
      email: 'senads@gmail.com',
      logout: 'Logout',
    },
    createWorkspaceModal: {
      createWorkspace: 'Create workspace',
      note: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
      workspaceTextfieldLabel: 'Workspace name:',
      workspaceTextfieldPlaceholder: 'Name',
      appIdLabel: 'App ID:',
      appIdPlaceholder: 'Apple ID',
      appClientSecretLabel: 'App client secret:',
      appClientSecretPlaceholder: 'Client secret',
      objectIdLabel: 'Object ID:',
      objectIdPlaceholder: 'Object ID',
    },
    search: {
      searchTitle: 'Search for template architectures',
      browseTitle: 'What do you want to create today?',
      browseTemplates: 'Or browse more templates',
      textfieldPlaceholder: 'Describe your needs (key words)',
      generate: 'Generate',
      tryThis: 'Try this:',
      lastViewed: 'Last viewed',
      mostInstalled: 'Most installed',
      newest: 'Newest',
      oldest: 'Oldest',
    },
    templates: {
      templates: 'Templates',
    },
    tourPopup: {
      title: 'Take a quick tour of the file browser?',
      content:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      noThanks: 'No, thanks',
      yes: 'Yes',
    },
  },
  workspacePage: {
    tabNames: {
      firstWorkspace: 'Workspace 1',
      secondWorkspace: 'Workspace 2',
      thirdWorkspace: 'Workspace 3',
    },
    profileHeader: {
      name: 'Senad Senadovic',
    },
    menuItems: {
      labelName: 'Lorem ipsum',
      additionalResources: 'Additional resources',
      verificate: 'Verificate',
    },
  },
  auth: {
    loginText: 'Login',
    signUp: 'Sign Up',
    welcomeTo: 'Welcome to',
    corePlatform: 'Core Platform',
    note: 'Kindly fill in your details below to create an account',
    login: {
      forgotPassword: 'Forgot Password?',
      signIn: 'Sign In',
      rememberMe: 'Remember me',
      emailLabel: 'Email address:',
      passwordLabel: 'Password:',
      emailPlaceHolder: 'Email',
      passwordPlaceHolder: '********',
    },
    registration: {
      usernameLabel: 'Username:',
      emailLabel: 'Email address:',
      passwordLabel: 'Password:',
      usernamePlaceHolder: 'Username',
      emailPlaceHolder: 'Email',
      passwordPlaceHolder: '********',
      termsAndConditions: 'I agree to terms & conditions',
      registerAccount: 'Register account',
    },
    socialAuthButtons: {
      or: 'Or',
      signInWithGoogle: 'Sign In With Google',
      registerWithGoogle: 'Register With Google',
      signInWithMicrosoft: 'Sign In With Microsoft',
      registerWithMicrosoft: 'Register With Microsoft',
    },
  },
  pricingPage: {
    ourOffer: {
      title: 'Choose the plan that fits your needs.',
      mostPopular: 'Most popular',
      benefitText: 'All benefits of',
      monthly: 'Monthly',
      annually: 'Annually',
      compareFeaturesTitle: 'Compare all features',
      feature: 'Lorem ipsum',
    },
  },
  monthlyPlans: [
    {
      title: 'Starter',
      description:
        'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
      price: '$0 /monthly',
      features: ['Lorem Ipsum', 'Lorem Ipsum', 'Lorem Ipsum', 'Lorem Ipsum'],
      buttonText: 'Start free trial',
    },
    {
      title: 'Premium',
      description:
        'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
      price: '$599 /monthly',
      features: [
        'All benefits of Starter, plus:',
        'Lorem Ipsum',
        'Lorem Ipsum',
        'Lorem Ipsum',
        'Lorem Ipsum',
        'Lorem Ipsum',
        'Lorem Ipsum',
      ],
      buttonText: 'Buy now',
      popular: true,
    },
    {
      title: 'Enterprise',
      description:
        'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
      price: '$1000 /monthly',
      features: [
        'All benefits of Premium, plus:',
        'Lorem Ipsum',
        'Lorem Ipsum',
        'Lorem Ipsum',
        'Lorem Ipsum',
        'Lorem Ipsum',
        'Lorem Ipsum',
      ],
      buttonText: 'Buy now',
    },
  ],
  annuallyPlans: [
    {
      title: 'Starter',
      description:
        'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
      price: '$0 /monthly',
      features: ['Lorem Ipsum', 'Lorem Ipsum', 'Lorem Ipsum', 'Lorem Ipsum'],
      buttonText: 'Start free trial',
    },
    {
      title: 'Premium',
      description:
        'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
      price: '$1599 /monthly',
      features: [
        'All benefits of Starter, plus:',
        'Lorem Ipsum',
        'Lorem Ipsum',
        'Lorem Ipsum',
        'Lorem Ipsum',
        'Lorem Ipsum',
        'Lorem Ipsum',
      ],
      buttonText: 'Buy now',
      popular: true,
    },
    {
      title: 'Enterprise',
      description:
        'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
      price: '$1999 /monthly',
      features: [
        'All benefits of Premium, plus:',
        'Lorem Ipsum',
        'Lorem Ipsum',
        'Lorem Ipsum',
        'Lorem Ipsum',
        'Lorem Ipsum',
        'Lorem Ipsum',
      ],
      buttonText: 'Buy now',
    },
  ],
  featureComparison: [
    {
      name: 'Lorem Ipsum',
      starter: '',
      premium: '',
      enterprise: '',
    },
    {
      name: 'Lorem Ipsum is simply dummy text',
      starter: false,
      premium: true,
      enterprise: true,
    },
    {
      name: 'Lorem dummy text ',
      starter: 'Unlimited',
      premium: true,
      enterprise: true,
    },
    {
      name: 'Lorem Ipsum is simply dummy text',
      starter: 'Unlimited',
      premium: true,
      enterprise: true,
    },
    {
      name: 'Lorem Ipsum is simply dummy text',
      starter: 'Unlimited',
      premium: true,
      enterprise: true,
    },
    {
      name: 'Lorem Ipsum',
      starter: '',
      premium: '',
      enterprise: '',
    },
    {
      name: 'Lorem Ipsum is simply dummy text',
      starter: false,
      premium: true,
      enterprise: true,
    },
    {
      name: 'Lorem Ipsum is simply dummy text',
      starter: false,
      premium: true,
      enterprise: true,
    },
    {
      name: 'Lorem Ipsum',
      starter: '',
      premium: '',
      enterprise: '',
    },
    {
      name: 'Lorem Ipsum is simply dummy text',
      starter: false,
      premium: true,
      enterprise: true,
    },
    {
      name: 'Lorem',
      starter: 'Unlimited',
      premium: true,
      enterprise: true,
    },
    {
      name: 'Lorem Ipsum',
      starter: 'Unlimited',
      premium: true,
      enterprise: true,
    },
    {
      name: 'Lorem Ipsum is simply dummy text',
      starter: false,
      premium: true,
      enterprise: true,
    },
    {
      name: 'Lorem',
      starter: '',
      premium: '',
      enterprise: '',
    },
    {
      name: 'Lorem Ipsum is simply dummy text',
      starter: false,
      premium: true,
      enterprise: true,
    },
    {
      name: 'Lorem dummy text',
      starter: 'Unlimited',
      premium: true,
      enterprise: true,
    },
    {
      name: 'Lorem Ipsum is simply dummy text',
      starter: 'Unlimited',
      premium: true,
      enterprise: true,
    },
    {
      name: 'Lorem',
      starter: 'Unlimited',
      premium: true,
      enterprise: true,
    },
  ],
};
